# Generated by Django 5.0.4 on 2024-07-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create",
            new_name="created",
        ),
    ]
