# Generated by Django 5.0.4 on 2024-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_updated_post_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=250),
        ),
    ]
