# Generated by Django 5.0.7 on 2024-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_delete_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
    ]
