# Generated by Django 5.0.7 on 2024-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, upload_to="portfolio/")),
            ],
        ),
    ]
