# Generated by Django 5.0.7 on 2024-10-22 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
