# Generated by Django 5.0.7 on 2024-10-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="about",
            old_name="date",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="city",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="about",
            name="state",
        ),
        migrations.RemoveField(
            model_name="about",
            name="street",
        ),
        migrations.AddIndex(
            model_name="about",
            index=models.Index(
                fields=["created_at"], name="blog_about_created_93b75d_idx"
            ),
        ),
    ]
