# Generated by Django 5.0.7 on 2024-11-03 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_rename_postal_code_about_zip_code_about_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="cv",
            field=models.FileField(default=django.utils.timezone.now, upload_to="cvs/"),
            preserve_default=False,
        ),
    ]
